<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetTitle("Поиск"); ?><?
// $APPLICATION->IncludeComponent(
// 	"bitrix:search.page", 
// 	"clear2", 
// 	array(
// 		"USE_SUGGEST" => "Y",
// 		"SHOW_ITEM_TAGS" => "N",
// 		"SHOW_ITEM_DATE_CHANGE" => "N",
// 		"SHOW_ORDER_BY" => "N",
// 		"SHOW_TAGS_CLOUD" => "N",
// 		"AJAX_MODE" => "Y",
// 		"RESTART" => "Y",
// 		"NO_WORD_LOGIC" => "N",
// 		"USE_LANGUAGE_GUESS" => "N",
// 		"CHECK_DATES" => "N",
// 		"USE_TITLE_RANK" => "Y",
// 		"DEFAULT_SORT" => "rank",
// 		"FILTER_NAME" => "",
// 		"SHOW_WHERE" => "N",
// 		"SHOW_WHEN" => "N",
// 		"PAGE_RESULT_COUNT" => "20",
// 		"CACHE_TYPE" => "A",
// 		"CACHE_TIME" => "3600",
// 		"DISPLAY_TOP_PAGER" => "Y",
// 		"DISPLAY_BOTTOM_PAGER" => "Y",
// 		"PAGER_TITLE" => "Результаты поиска",
// 		"PAGER_SHOW_ALWAYS" => "N",
// 		"PAGER_TEMPLATE" => "",
// 		"arrFILTER" => array(
// 			0 => "iblock_catalog1Cv83",
// 		),
// 		"arrFILTER_iblock_catalog1Cv83" => array(
// 			0 => "86",
// 			1 => "87",
// 			2 => "88",
// 		),
// 		"AJAX_OPTION_JUMP" => "N",
// 		"AJAX_OPTION_STYLE" => "Y",
// 		"AJAX_OPTION_HISTORY" => "N",
// 		"AJAX_OPTION_ADDITIONAL" => "",
// 		"COMPONENT_TEMPLATE" => "clear2",
// 		"STRUCTURE_FILTER" => "structure",
// 		"NAME_TEMPLATE" => "",
// 		"SHOW_LOGIN" => "Y",
// 		"TAGS_SORT" => "NAME",
// 		"TAGS_PAGE_ELEMENTS" => "150",
// 		"TAGS_PERIOD" => "",
// 		"TAGS_URL_SEARCH" => "",
// 		"TAGS_INHERIT" => "Y",
// 		"FONT_MAX" => "50",
// 		"FONT_MIN" => "10",
// 		"COLOR_NEW" => "000000",
// 		"COLOR_OLD" => "C8C8C8",
// 		"PERIOD_NEW_TAGS" => "",
// 		"SHOW_CHAIN" => "Y",
// 		"COLOR_TYPE" => "Y",
// 		"WIDTH" => "100%",
// 		"arrWHERE" => array(
// 			0 => "iblock_catalog1Cv83",
// 		),
// 		"COMPOSITE_FRAME_MODE" => "A",
// 		"COMPOSITE_FRAME_TYPE" => "AUTO"
// 	),
// 	false
// );
?>

    <div class="container mb-3">
        <div class="section section_padding">
            <? $APPLICATION->IncludeComponent(
                "bitrix:catalog.search",
                "search.profnastil",
                array(
                    "ACTION_VARIABLE" => "action",
                    "AJAX_MODE" => "N",
                    "AJAX_OPTION_ADDITIONAL" => "",
                    "AJAX_OPTION_HISTORY" => "N",
                    "AJAX_OPTION_JUMP" => "N",
                    "AJAX_OPTION_STYLE" => "Y",
                    "BASKET_URL" => "/personal/basket.php",
                    "CACHE_TIME" => "36000000",
                    "CACHE_TYPE" => "A",
                    "CHECK_DATES" => "N",
                    "CONVERT_CURRENCY" => "N",
                    "DETAIL_URL" => "/catalog/#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
                    "DISPLAY_BOTTOM_PAGER" => "Y",
                    "DISPLAY_COMPARE" => "N",
                    "DISPLAY_TOP_PAGER" => "N",
                    "ELEMENT_SORT_FIELD" => "sort",
                    "ELEMENT_SORT_FIELD2" => "id",
                    "ELEMENT_SORT_ORDER" => "asc",
                    "ELEMENT_SORT_ORDER2" => "desc",
                    "HIDE_NOT_AVAILABLE" => "N",
                    "HIDE_NOT_AVAILABLE_OFFERS" => "N",
                    "IBLOCK_ID" => "113",
                    "IBLOCK_TYPE" => "catalog1Cv83",
                    "LINE_ELEMENT_COUNT" => "3",
                    "NO_WORD_LOGIC" => "N",
                    "OFFERS_CART_PROPERTIES" => array(),
                    "OFFERS_FIELD_CODE" => array("", ""),
                    "OFFERS_LIMIT" => "5",
                    "OFFERS_PROPERTY_CODE" => array("", ""),
                    "OFFERS_SORT_FIELD" => "sort",
                    "OFFERS_SORT_FIELD2" => "id",
                    "OFFERS_SORT_ORDER" => "asc",
                    "OFFERS_SORT_ORDER2" => "desc",
                    "PAGER_DESC_NUMBERING" => "N",
                    "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
                    "PAGER_SHOW_ALL" => "N",
                    "PAGER_SHOW_ALWAYS" => "N",
                    "PAGER_TEMPLATE" => "round",
                    "PAGER_TITLE" => "Товары",
                    "PAGE_ELEMENT_COUNT" => "30",
                    "PRICE_CODE" => array("BASE", "ИП", "РозничнаяИМ", "Gektar", "Типовые правила продаж"),
                    "PRICE_VAT_INCLUDE" => "Y",
                    "PRODUCT_ID_VARIABLE" => "id",
                    "PRODUCT_PROPERTIES" => "",
                    "PRODUCT_PROPS_VARIABLE" => "prop",
                    "PRODUCT_QUANTITY_VARIABLE" => "quantity",
                    "PROPERTY_CODE" => array("", ""),
                    "RESTART" => "N",
                    "SECTION_ID_VARIABLE" => "SECTION_ID",
                    "SECTION_URL" => "",
                    "SHOW_PRICE_COUNT" => "1",
                    "USE_LANGUAGE_GUESS" => "Y",
                    "USE_PRICE_COUNT" => "N",
                    "USE_PRODUCT_QUANTITY" => "N",
                    "USE_SEARCH_RESULT_ORDER" => "N",
                    "USE_TITLE_RANK" => "N"
                )
            ); ?>
        </div>
    </div>
<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>